import { buildMachineHeroSummary } from "./view-models.js";
import type { MachinePanelRenderContext } from "./contracts.js";

export function renderMachinePanelView(context: MachinePanelRenderContext): string {
  const { state, activeMode, helpers } = context;
  const {
    escapeHtml,
    escapeAttribute,
    iconSvg,
    iconLabel,
    renderHeaderBadge,
    renderPanelHeader,
    renderInlineBadge,
    renderNoteRow,
    renderEmptyState,
    renderStatCard,
    renderInfoRow,
    formatInteger,
    formatPercent,
    formatCurrency,
    formatTimestamp
  } = helpers;
  const machine = state.machineAdvisory;
  const machineHero = buildMachineHeroSummary(machine);
  const groupedGuidance = {
    critical: machine.guidance.filter((entry) => entry.group === "critical-issues"),
    recommended: machine.guidance.filter((entry) => entry.group === "improvements"),
    optional: machine.guidance.filter((entry) => entry.group === "optional-optimizations")
  };

  const renderMachineTable = (headers: string[], rows: string[][]): string => `
    <div class="kc-table-shell">
      <table class="kc-data-table">
        <thead>
          <tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr>
        </thead>
        <tbody>
          ${rows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`).join("")}
        </tbody>
      </table>
    </div>
  `;

  const renderMachineStateChip = (active: boolean, activeLabel: string, inactiveLabel: string): string =>
    `<span class="kc-machine-state ${active ? "is-active" : "is-inactive"}">${escapeHtml(active ? activeLabel : inactiveLabel)}</span>`;

  const renderFreshnessRow = (meta: { status: "fresh" | "cached" | "partial"; updatedAt: string; reason?: string }): string => `
    <div class="kc-inline-badges kc-machine-freshness">
      ${renderHeaderBadge(meta.status, meta.status === "fresh" ? "success" : meta.status === "cached" ? "neutral" : "warn")}
      ${renderInlineBadge(meta.updatedAt ? formatTimestamp(meta.updatedAt) : "unknown time")}
      ${meta.reason ? renderInlineBadge(meta.reason) : ""}
    </div>
  `;

  const formatSectionSummary = (meta: { status: "fresh" | "cached" | "partial"; updatedAt: string; reason?: string }): string =>
    `${meta.status}${meta.updatedAt ? ` · ${formatTimestamp(meta.updatedAt)}` : ""}${meta.reason ? ` · ${meta.reason}` : ""}`;

  const renderGuidanceRow = (entry: typeof machine.guidance[number]): string => {
    const actions = [entry.fixCommand, entry.hintCommand].filter(Boolean).join(" | ");
    return `
      <div class="kc-note-row">
        <div>
          <strong>${escapeHtml(entry.message)}</strong>
          <span>${escapeHtml(entry.reason ?? `section: ${entry.section}`)}</span>
          <span>${escapeHtml(entry.impact)}</span>
        </div>
        <em class="${entry.priority === "critical" ? "tone-warn" : ""}">${escapeHtml(actions || entry.priority)}</em>
      </div>
    `;
  };

  const renderGuidanceGroup = (title: string, entries: typeof machine.guidance): string => `
    <div class="kc-stack-block">
      <p class="kc-stack-label">${escapeHtml(title)}</p>
      <div class="kc-stack-list">
        ${entries.map((entry) => renderGuidanceRow(entry)).join("")}
      </div>
    </div>
  `;

  return `
    <div class="kc-view-shell">
      <section class="kc-view-header">
        <div>
          <p class="kc-view-kicker">Machine Advisory</p>
          <h1>System Limitations</h1>
          <p>Read-only machine limitations and repair guidance. This never overrides repo-local Kiwi state. Generated by ${escapeHtml(machine.generatedBy)}.</p>
        </div>
        ${renderHeaderBadge(machine.stale ? "stale" : "fresh", machine.stale ? "warn" : "success")}
      </section>

      <section class="kc-panel kc-panel-primary">
        <div class="kc-panel-heading">
          <div class="kc-panel-kicker">
            ${iconLabel(iconSvg("system"), "Setup Readiness")}
            ${renderHeaderBadge(machineHero.overallStatus, machineHero.overallTone === "success" ? "success" : "warn")}
          </div>
          <h1>${escapeHtml(machineHero.title)}</h1>
          <p>${escapeHtml(machineHero.detail)}</p>
        </div>
        <div class="kc-two-column">
          <section class="kc-subpanel">
            <div class="kc-stack-list">
              ${renderNoteRow(machineHero.bestHeuristicLabel, machineHero.bestHeuristicValue, "Heuristic completeness from inspected machine signals.")}
              ${renderNoteRow(machineHero.strongestGapLabel, machineHero.overallStatus, machineHero.strongestGapDetail)}
            </div>
          </section>
          <section class="kc-subpanel">
            <div class="kc-stack-list">
              ${renderNoteRow(machineHero.nextFixLabel, machineHero.nextFixCommand, "Run this next to improve machine readiness or inspect the remaining gap.")}
            </div>
          </section>
        </div>
      </section>

      <div class="kc-stat-grid">
        ${renderStatCard("Critical", String(machine.systemHealth.criticalCount), "fix first", machine.systemHealth.criticalCount > 0 ? "critical" : "neutral")}
        ${renderStatCard("Warnings", String(machine.systemHealth.warningCount), "recommended actions", machine.systemHealth.warningCount > 0 ? "warn" : "neutral")}
        ${renderStatCard("Healthy", String(machine.systemHealth.okCount), "healthy checks", "success")}
        ${renderStatCard("Planning Heuristic", `${machine.optimizationScore.planning.score}%`, `${machine.optimizationScore.planning.earnedPoints}/${machine.optimizationScore.planning.maxPoints} signal points`, "neutral")}
        ${renderStatCard("Execution Heuristic", `${machine.optimizationScore.execution.score}%`, `${machine.optimizationScore.execution.earnedPoints}/${machine.optimizationScore.execution.maxPoints} signal points`, "neutral")}
        ${renderStatCard("Assistant Heuristic", `${machine.optimizationScore.assistant.score}%`, `${machine.optimizationScore.assistant.earnedPoints}/${machine.optimizationScore.assistant.maxPoints} signal points`, "neutral")}
        ${renderStatCard("Claude MCPs", String(machine.mcpInventory.claudeTotal), "configured servers", "neutral")}
        ${renderStatCard("Codex MCPs", String(machine.mcpInventory.codexTotal), "configured servers", "neutral")}
        ${renderStatCard("Copilot MCPs", String(machine.mcpInventory.copilotTotal), "configured servers", "neutral")}
        ${renderStatCard("Skills", String(machine.skillsCount), "agent skills in ~/.agents/skills", "neutral")}
        ${renderStatCard("Window", `${machine.windowDays} days`, machine.note, machine.stale ? "warn" : "success")}
      </div>

      <section class="kc-panel">
        ${renderPanelHeader("Top Signals", "Machine-level limits that matter first for the current repo and workflow state.")}
        <div class="kc-stack-list">
          ${renderNoteRow("Critical issues", String(machine.systemHealth.criticalCount), machine.systemHealth.criticalCount > 0 ? "Fix these before relying on machine hints." : "No critical machine blockers are currently active.")}
          ${renderNoteRow("Warnings", String(machine.systemHealth.warningCount), machine.systemHealth.warningCount > 0 ? "Recommended improvements are available." : "No active advisory warnings right now.")}
          ${renderNoteRow("Usage window", `${machine.windowDays} days`, machine.usage.codex.available || machine.usage.claude.available ? "Recent machine telemetry is available." : "Token tracking is currently limited.")}
        </div>
      </section>

      <section class="kc-panel">
        ${renderPanelHeader("Setup Summary", "Borrowed from ai-setup-style machine completion checks, but kept repo-local and read-only.")}
        <div class="kc-two-column">
          <section class="kc-subpanel">
            <div class="kc-stack-list">
              ${renderNoteRow("Installed tools", `${machine.setupSummary.installedTools.readyCount}/${machine.setupSummary.installedTools.totalCount}`, "Machine-local toolchain presence across the tracked inventory.")}
              ${renderNoteRow("Healthy configs", `${machine.setupSummary.healthyConfigs.readyCount}/${machine.setupSummary.healthyConfigs.totalCount}`, "Validated config and hook surfaces across Claude, Codex, and Copilot.")}
              ${renderNoteRow("Active token layers", String(machine.setupSummary.activeTokenLayers.length), machine.setupSummary.activeTokenLayers.length > 0 ? machine.setupSummary.activeTokenLayers.join(", ") : "No token-optimization layers are currently active.")}
            </div>
          </section>
          <section class="kc-subpanel">
            <div class="kc-stack-list">
              ${renderNoteRow("Planning runtime", machine.setupSummary.readyRuntimes.planning ? "ready" : "needs work", machine.optimizationScore.planning.activeSignals.join(", ") || "No active planning signals detected.")}
              ${renderNoteRow("Execution runtime", machine.setupSummary.readyRuntimes.execution ? "ready" : "needs work", machine.optimizationScore.execution.activeSignals.join(", ") || "No active execution signals detected.")}
              ${renderNoteRow("Assistant runtime", machine.setupSummary.readyRuntimes.assistant ? "ready" : "needs work", machine.optimizationScore.assistant.activeSignals.join(", ") || "No active assistant signals detected.")}
            </div>
          </section>
        </div>
      </section>

      <section class="kc-panel">
        ${renderPanelHeader("Optimization Heuristic", "Heuristic completeness score calculated from inspected machine signals. This is advisory only and never overrides repo-local Kiwi state.")}
        <div class="kc-two-column">
          <section class="kc-subpanel">
            <div class="kc-stack-list">
              ${renderNoteRow("Planning", `${machine.optimizationScore.planning.score}%`, `${machine.optimizationScore.planning.earnedPoints}/${machine.optimizationScore.planning.maxPoints} points · active: ${machine.optimizationScore.planning.activeSignals.join(", ") || "none"}`)}
              ${renderNoteRow("Execution", `${machine.optimizationScore.execution.score}%`, `${machine.optimizationScore.execution.earnedPoints}/${machine.optimizationScore.execution.maxPoints} points · active: ${machine.optimizationScore.execution.activeSignals.join(", ") || "none"}`)}
              ${renderNoteRow("Assistant", `${machine.optimizationScore.assistant.score}%`, `${machine.optimizationScore.assistant.earnedPoints}/${machine.optimizationScore.assistant.maxPoints} points · active: ${machine.optimizationScore.assistant.activeSignals.join(", ") || "none"}`)}
            </div>
          </section>
          <section class="kc-subpanel">
            <div class="kc-stack-list">
              ${renderNoteRow("Planning gaps", String(machine.optimizationScore.planning.missingSignals.length), machine.optimizationScore.planning.missingSignals.join(", ") || "No planning gaps detected.")}
              ${renderNoteRow("Execution gaps", String(machine.optimizationScore.execution.missingSignals.length), machine.optimizationScore.execution.missingSignals.join(", ") || "No execution gaps detected.")}
              ${renderNoteRow("Assistant gaps", String(machine.optimizationScore.assistant.missingSignals.length), machine.optimizationScore.assistant.missingSignals.join(", ") || "No assistant gaps detected.")}
            </div>
          </section>
        </div>
      </section>

      <section class="kc-panel">
        ${renderPanelHeader("Machine Setup Provenance", "Structured provenance of the machine-local setup, grouped by phase.")}
        ${renderFreshnessRow(machine.sections.setupPhases)}
        ${machine.setupPhases.length > 0
          ? machine.setupPhases.map((phase) => `
              <div class="kc-stack-block">
                <p class="kc-stack-label">${escapeHtml(phase.phase)}</p>
                <div class="kc-stack-list">
                  ${phase.items.map((item) => renderNoteRow(
                    describeMachineUiName(item.name),
                    item.active ? "active" : "inactive",
                    `${describeMachineUiDescription(item.name, item.description)} · ${describeMachineUiLocation(item.location)}`
                  )).join("")}
                </div>
              </div>
            `).join('<div class="kc-divider"></div>')
          : renderEmptyState("No machine-local setup provenance is available.")}
      </section>

      <section class="kc-panel">
        ${renderPanelHeader("Config Health", "Machine-level config and hook surfaces.")}
        ${renderFreshnessRow(machine.sections.configHealth)}
        ${machine.configHealth.length > 0
          ? renderMachineTable(
              ["Config", "Status", "Description"],
              machine.configHealth.map((entry) => [
                escapeHtml(entry.path),
                renderMachineStateChip(entry.healthy, "healthy", "issue"),
                escapeHtml(entry.description)
              ])
            )
          : renderEmptyState("No config health data is available.")}
      </section>

      <section class="kc-panel">
        ${renderPanelHeader(`Token Usage (Last ${machine.windowDays} Days)`, "Measured usage from Claude and Codex local sources.")}
        ${renderFreshnessRow(machine.sections.usage)}
        <div class="kc-two-column">
          <section class="kc-subpanel">
            ${renderPanelHeader("Claude Code (via ccusage)", machine.usage.claude.note)}
            <div class="kc-stack-list">
              ${renderNoteRow("Total", machine.usage.claude.available ? `${formatInteger(machine.usage.claude.totals.totalTokens)} tokens` : "unavailable", machine.usage.claude.totals.totalCost != null ? `cache ${formatPercent(machine.usage.claude.totals.cacheHitRatio)} · cost ${formatCurrency(machine.usage.claude.totals.totalCost)}` : machine.usage.claude.note)}
            </div>
            <div class="kc-divider"></div>
            ${machine.usage.claude.days.length > 0
              ? renderMachineTable(
                  ["Date", "Input", "Output", "Cache Read", "Cost", "Models"],
                  machine.usage.claude.days.map((day) => [
                    escapeHtml(day.date),
                    escapeHtml(formatInteger(day.inputTokens)),
                    escapeHtml(formatInteger(day.outputTokens)),
                    escapeHtml(formatInteger(day.cacheReadTokens)),
                    escapeHtml(formatCurrency(day.totalCost)),
                    escapeHtml(day.modelsUsed.join(", ") || "—")
                  ])
                )
              : renderEmptyState(machine.usage.claude.note)}
          </section>
          <section class="kc-subpanel">
            ${renderPanelHeader("Codex (via session logs)", machine.usage.codex.note)}
            <div class="kc-stack-list">
              ${renderNoteRow("Total", machine.usage.codex.available ? `${formatInteger(machine.usage.codex.totals.totalTokens)} tokens` : "unavailable", machine.usage.codex.available ? `cache ${formatPercent(machine.usage.codex.totals.cacheHitRatio)} · sessions ${formatInteger(machine.usage.codex.totals.sessions)}` : machine.usage.codex.note)}
            </div>
            <div class="kc-divider"></div>
            ${machine.usage.codex.days.length > 0
              ? renderMachineTable(
                  ["Date", "Input", "Output", "Cached", "Sessions"],
                  machine.usage.codex.days.map((day) => [
                    escapeHtml(day.date),
                    escapeHtml(formatInteger(day.inputTokens)),
                    escapeHtml(formatInteger(day.outputTokens)),
                    escapeHtml(formatInteger(day.cachedInputTokens)),
                    escapeHtml(formatInteger(day.sessions))
                  ])
                )
              : renderEmptyState(machine.usage.codex.note)}
          </section>
        </div>
        <div class="kc-divider"></div>
        <div class="kc-stack-list">
          ${renderNoteRow("Copilot CLI", machine.usage.copilot.available ? "available" : "unavailable", machine.usage.copilot.note)}
        </div>
      </section>

      <section class="kc-panel">
        ${renderPanelHeader("Guidance", "Assistive machine-local suggestions and repo hints. These are advisory only and never auto-applied.")}
        ${renderFreshnessRow(machine.sections.guidance)}
        ${machine.guidance.length > 0
          ? `
            ${groupedGuidance.critical.length > 0 ? renderGuidanceGroup("Critical Issues", groupedGuidance.critical) : ""}
            ${groupedGuidance.recommended.length > 0 ? renderGuidanceGroup("Improvements", groupedGuidance.recommended) : ""}
            ${groupedGuidance.optional.length > 0 ? renderGuidanceGroup("Optional Optimizations", groupedGuidance.optional) : ""}
          `
          : renderEmptyState("No machine-local suggestions are currently recorded.")}
      </section>

      <section class="kc-panel">
        ${renderPanelHeader("System Details", "Expanded machine diagnostics for inspection mode.")}
        ${activeMode === "inspection"
          ? `
            <details class="kc-fold-card" open>
              <summary><strong>Toolchain inventory</strong><span>${escapeHtml(formatSectionSummary(machine.sections.inventory))}</span></summary>
              <div class="kc-fold-body">
                ${machine.inventory.length > 0
                  ? renderMachineTable(
                      ["Tool", "Version", "Phase", "Status"],
                      machine.inventory.map((tool) => [
                        escapeHtml(describeMachineUiName(tool.name)),
                        escapeHtml(tool.version),
                        escapeHtml(tool.phase),
                        renderMachineStateChip(tool.installed, "installed", "missing")
                      ])
                    )
                  : renderEmptyState("No machine-local tool inventory is available.")}
              </div>
            </details>
            <details class="kc-fold-card">
              <summary><strong>MCP servers</strong><span>${escapeHtml(formatSectionSummary(machine.sections.mcpInventory))}</span></summary>
              <div class="kc-fold-body">
                <div class="kc-info-grid">
                  ${renderInfoRow("Planning runtime", formatInteger(machine.mcpInventory.claudeTotal))}
                  ${renderInfoRow("Execution runtime", formatInteger(machine.mcpInventory.codexTotal))}
                  ${renderInfoRow("Assistant runtime", formatInteger(machine.mcpInventory.copilotTotal))}
                </div>
                <div class="kc-divider"></div>
                ${machine.mcpInventory.tokenServers.length > 0
                  ? renderMachineTable(
                      ["Server", "Planning", "Execution", "Assistant"],
                      machine.mcpInventory.tokenServers.map((server) => [
                        escapeHtml(describeMachineUiName(server.name)),
                        renderMachineStateChip(server.claude, "active", "—"),
                        renderMachineStateChip(server.codex, "active", "—"),
                        renderMachineStateChip(server.copilot, "active", "—")
                      ])
                    )
                  : renderEmptyState("No token-focused MCP inventory is available.")}
              </div>
            </details>
            <details class="kc-fold-card">
              <summary><strong>Optimization layers</strong><span>${escapeHtml(formatSectionSummary(machine.sections.optimizationLayers))}</span></summary>
              <div class="kc-fold-body">
                ${machine.optimizationLayers.length > 0
                  ? renderMachineTable(
                      ["Layer", "Savings", "Planning", "Execution", "Assistant"],
                      machine.optimizationLayers.map((layer) => [
                        escapeHtml(describeMachineUiName(layer.name)),
                        escapeHtml(layer.savings),
                        renderMachineStateChip(layer.claude, "yes", "no"),
                        renderMachineStateChip(layer.codex, "yes", "no"),
                        renderMachineStateChip(layer.copilot, "yes", "no")
                      ])
                    )
                  : renderEmptyState("No optimization layer data is available.")}
              </div>
            </details>
            <details class="kc-fold-card">
              <summary><strong>Config health</strong><span>${escapeHtml(formatSectionSummary(machine.sections.configHealth))}</span></summary>
              <div class="kc-fold-body">
                ${machine.configHealth.length > 0
                  ? renderMachineTable(
                      ["Config", "Status", "Description"],
                      machine.configHealth.map((entry) => [
                        escapeHtml(entry.path),
                        renderMachineStateChip(entry.healthy, "healthy", "issue"),
                        escapeHtml(entry.description)
                      ])
                    )
                  : renderEmptyState("No config health data is available.")}
              </div>
            </details>
          `
          : renderEmptyState("Switch to inspection mode to expand raw machine internals.")}
      </section>
    </div>
  `;
}

function describeMachineUiName(name: string): string {
  const normalized = name.trim().toLowerCase();
  if (normalized === "code-review-graph") {
    return "Structural repo graph";
  }
  if (normalized === "omc") {
    return "Planning orchestration layer";
  }
  if (normalized === "omx") {
    return "Execution orchestration layer";
  }
  if (normalized === "lean-ctx") {
    return "Shell compression layer";
  }
  if (normalized === "context-mode") {
    return "Sandboxed context layer";
  }
  if (normalized === "ccusage") {
    return "Usage telemetry collector";
  }
  if (normalized === "copilot") {
    return "Assistant CLI";
  }
  if (normalized === "ai-setup script") {
    return "Machine bootstrap helper";
  }
  if (normalized.startsWith("copilot plugins")) {
    return name.replace(/copilot plugins/i, "Assistant plugins");
  }
  return name.replace(/[-_]/g, " ");
}

function describeMachineUiDescription(name: string, description: string): string {
  const normalized = name.trim().toLowerCase();
  if (normalized === "code-review-graph") {
    return "Structural repo search and graph-backed code lookup";
  }
  if (normalized === "omc") {
    return "Multi-agent planning and review orchestration";
  }
  if (normalized === "omx") {
    return "Multi-agent execution orchestration";
  }
  if (normalized === "lean-ctx") {
    return "Shell output compression for lower-noise local runs";
  }
  if (normalized === "context-mode") {
    return "Sandboxed tool output and context shaping";
  }
  if (normalized === "ccusage") {
    return "Machine-local usage telemetry source";
  }
  if (normalized === "copilot") {
    return "Editor assistant command-line surface";
  }
  if (normalized === "ai-setup script") {
    return "Machine bootstrap entrypoint";
  }
  return description;
}

function describeMachineUiLocation(location: string): string {
  return location
    .replace(/Claude Code/gi, "planning runtime")
    .replace(/Codex/gi, "execution runtime")
    .replace(/Copilot CLI/gi, "assistant runtime")
    .replace(/~\/\.copilot/gi, "~/.assistant")
    .replace(/~\/\.claude/gi, "~/.planner")
    .replace(/~\/\.codex/gi, "~/.execution");
}
