import path from "node:path";
import type { ContextSelection } from "./context-selector.js";
import { writeText } from "../utils/fs.js";

export interface GeneratedInstructions {
  goal: string;
  allowedFiles: string[];
  forbiddenPatterns: string[];
  steps: string[];
  constraints: string[];
  raw: string;
}

const DEFAULT_CONSTRAINTS = [
  "Minimal edits only — change only what the goal requires.",
  "No full repository scanning — use only the allowed files listed above.",
  "No refactoring unless the goal explicitly requires it.",
  "No unnecessary web search — repo-local context is sufficient.",
  "No over-explaining — keep responses focused on the goal.",
  "Do not create files unless the goal requires new functionality.",
  "Do not modify tests unless the goal is about testing.",
  "Validate changes compile and pass existing tests before finishing."
];

export function generateInstructions(
  task: string,
  selection: ContextSelection
): GeneratedInstructions {
  const steps = deriveSteps(task, selection);
  const forbiddenPatterns = [
    ...selection.exclude,
    "**/.env*",
    "**/secrets/**",
    "**/credentials/**"
  ];

  const raw = renderInstructionDocument({
    goal: task,
    allowedFiles: selection.include,
    forbiddenPatterns,
    steps,
    constraints: DEFAULT_CONSTRAINTS
  });

  return {
    goal: task,
    allowedFiles: selection.include,
    forbiddenPatterns,
    steps,
    constraints: DEFAULT_CONSTRAINTS,
    raw
  };
}

function deriveSteps(task: string, selection: ContextSelection): string[] {
  const steps: string[] = [];
  const { signals } = selection;

  if (signals.changedFiles.length > 0) {
    steps.push(
      `Read the changed files first: ${signals.changedFiles.slice(0, 5).join(", ")}`
    );
  }

  if (signals.importNeighbors.length > 0) {
    steps.push(
      `Review import dependencies: ${signals.importNeighbors.slice(0, 5).join(", ")}`
    );
  }

  steps.push(`Implement the goal: ${task}`);

  if (signals.changedFiles.some((f) => f.endsWith(".test.ts") || f.endsWith(".test.js") || f.endsWith("_test.py"))) {
    steps.push("Run affected tests to verify the change.");
  } else {
    steps.push("Run existing tests to verify no regressions.");
  }

  steps.push("Review the diff for minimal scope — remove any unrelated changes.");

  return steps;
}

function renderInstructionDocument(instructions: {
  goal: string;
  allowedFiles: string[];
  forbiddenPatterns: string[];
  steps: string[];
  constraints: string[];
}): string {
  const lines: string[] = [
    "# AI Task Instructions",
    "",
    "Generated by Kiwi Control. This document constrains AI tool behavior for the current task.",
    "",
    "## GOAL",
    "",
    instructions.goal,
    "",
    "## ALLOWED FILES",
    "",
    ...instructions.allowedFiles.map((f) => `- ${f}`),
    ...(instructions.allowedFiles.length === 0 ? ["- (no specific files selected — task may require broader exploration)"] : []),
    "",
    "## FORBIDDEN FILES",
    "",
    ...instructions.forbiddenPatterns.map((f) => `- ${f}`),
    "",
    "## STEPS",
    "",
    ...instructions.steps.map((s, i) => `${i + 1}. ${s}`),
    "",
    "## CONSTRAINTS",
    "",
    ...instructions.constraints.map((c) => `- ${c}`),
    ""
  ];

  return lines.join("\n");
}

export async function persistInstructions(
  targetRoot: string,
  instructions: GeneratedInstructions
): Promise<string> {
  const outputPath = path.join(
    targetRoot,
    ".agent",
    "context",
    "generated-instructions.md"
  );
  await writeText(outputPath, instructions.raw);
  return outputPath;
}
